### ISSUE TITLE
Configuration file is read from /usr/local/etc/ instead of /etc

### ISSUE THREAD

**Issue by albertoventurini** [fralalonde/autoroute#2]
According to the readme file, once `autoroute` is installed it should read its configuration from `/etc/autoroute.conf`.

Instead, it reads its configuration from `/usr/local/etc/autoroute.conf`.

I guess the readme file should be updated to reflect the new location of the configuration file.

**Comment by fralalonde** [comment]
Ok, I'll try to fix it later today.

**Comment by fralalonde** [comment]
I updated the readme with correct filename. Closing issue.
